# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala

scala:
  - 2.10.4
  
script: sbt clean test scripted

# Testing with OpenJDK7 as well just to be adventurous!
jdk:
  - oraclejdk7
  - openjdk7

# Custom notification settings
notifications:
  email:
    recipients:
      - jan@eigengo.com

